### PR TITLE
Made changes on modified:  Home.jsx, AddSub.jsx, SubCard.jsx, displayBox.jsx

### PR DESCRIPTION
**Pull request by 01001101CK**
Co-authored-by: Kelvin Van <90666201+KelvinVan1@users.noreply.github.com>
Co-authored-by: James Howat <97859901+jbhowat@users.noreply.github.com>
Co-authored-by: Ed Cho <106274379+edcho720@users.noreply.github.com>
Co-authored-by: Yufa Li <112290188+01001101CK@users.noreply.github.com>
Co-authored-by: Hashim Farah <70618821+Hashim-21@users.noreply.github.com>

### CODE REVIEW

**Review by KelvinVan1 — APPROVED** [review]
Congrats on the first pull request. Everything looks good nice work.

**Comment by 01001101CK** [comment]
Try this again!

**Review by KelvinVan1 — APPROVED** [review]
Great work!

**Review by edcho720 — APPROVED** [review]
Awesome job!

**Pull request merged**
